#! /bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0

if [ "x$1" = xconfigure ]; then
	if ! getent group snmp >/dev/null ; then
		 deluser --quiet --system snmp
	fi
	adduser --quiet --system --group --no-create-home --home /var/lib/snmp snmp
	chown -R snmp:snmp /var/lib/snmp
fi

if [ -f /var/run/agentx ]; then
	rm -f /var/run/agentx
fi

if [ ! -d /var/run/agentx ]; then
	mkdir -p /var/run/agentx
fi

#DEBHELPER#

exit 0
